import { BEZEMISI_BASE_URL } from "../constants";

export type DiscoveredCatalogueModel = {
  brandName: string;
  brandSlug: string;
  modelName: string;
  modelSlug: string;
  category?: string;
  bodyType?: string;
  detailUrl?: string;
  catalogueRangeKm?: number;
  cataloguePriceFrom?: number;
  priceUnavailable?: boolean;
  hasDetailPage: boolean;
};

export const DISCOVERED_CATALOGUE_MODELS: DiscoveredCatalogueModel[] = [
  {
    brandName: "BMW",
    brandSlug: "bmw",
    modelName: "BMW iX1",
    modelSlug: "ix1",
    category: "Kompaktní SUV",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/bmw/ix1`,
    catalogueRangeKm: 474,
    cataloguePriceFrom: 1_068_600,
    hasDetailPage: true,
  },
  {
    brandName: "Hyundai",
    brandSlug: "hyundai",
    modelName: "Hyundai KONA Electric",
    modelSlug: "kona-electric",
    category: "Kompaktní SUV",
    bodyType: "suv",
    catalogueRangeKm: 510,
    cataloguePriceFrom: 799_990,
    hasDetailPage: false,
  },
  {
    brandName: "Hyundai",
    brandSlug: "hyundai",
    modelName: "Hyundai INSTER",
    modelSlug: "inster",
    category: "Městský elektromobil",
    bodyType: "city",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/hyundai/inster`,
    catalogueRangeKm: 370,
    cataloguePriceFrom: 599_990,
    hasDetailPage: true,
  },
  {
    brandName: "Hyundai",
    brandSlug: "hyundai",
    modelName: "Hyundai IONIQ 2",
    modelSlug: "ioniq-2",
    category: "Městský elektromobil",
    bodyType: "city",
    catalogueRangeKm: 599,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "Hyundai",
    brandSlug: "hyundai",
    modelName: "Hyundai IONIQ 5",
    modelSlug: "ioniq-5",
    category: "SUV",
    bodyType: "suv",
    catalogueRangeKm: 570,
    cataloguePriceFrom: 1_119_990,
    hasDetailPage: false,
  },
  {
    brandName: "Opel",
    brandSlug: "opel",
    modelName: "Opel Astra Electric",
    modelSlug: "astra-electric",
    category: "Kompakt",
    bodyType: "hatchback",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/opel/astra-electric`,
    catalogueRangeKm: 418,
    cataloguePriceFrom: 1_049_990,
    hasDetailPage: true,
  },
  {
    brandName: "Opel",
    brandSlug: "opel",
    modelName: "Opel Grandland Electric",
    modelSlug: "grandland-electric",
    category: "SUV",
    bodyType: "suv",
    catalogueRangeKm: 582,
    cataloguePriceFrom: 1_079_990,
    hasDetailPage: false,
  },
  {
    brandName: "Renault",
    brandSlug: "renault",
    modelName: "Renault 5",
    modelSlug: "renault-5",
    category: "Městský elektromobil",
    bodyType: "hatchback",
    catalogueRangeKm: 410,
    cataloguePriceFrom: 675_000,
    hasDetailPage: false,
  },
  {
    brandName: "Peugeot",
    brandSlug: "peugeot",
    modelName: "Peugeot E-3008",
    modelSlug: "e-3008",
    category: "SUV",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/peugeot/e-3008`,
    catalogueRangeKm: 698,
    cataloguePriceFrom: 1_079_000,
    hasDetailPage: true,
  },
  {
    brandName: "Volvo",
    brandSlug: "volvo",
    modelName: "Volvo EX30",
    modelSlug: "ex30",
    category: "Kompaktní SUV",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/volvo/ex30`,
    catalogueRangeKm: 660,
    cataloguePriceFrom: 895_000,
    hasDetailPage: true,
  },
  {
    brandName: "Volvo",
    brandSlug: "volvo",
    modelName: "Volvo EX60",
    modelSlug: "ex60",
    category: "SUV",
    bodyType: "suv",
    catalogueRangeKm: 805,
    cataloguePriceFrom: 1_562_000,
    hasDetailPage: false,
  },
  {
    brandName: "Škoda",
    brandSlug: "skoda",
    modelName: "Škoda Peaq",
    modelSlug: "peaq",
    category: "SUV",
    bodyType: "suv",
    catalogueRangeKm: 600,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "Škoda",
    brandSlug: "skoda",
    modelName: "Škoda Epiq",
    modelSlug: "epiq",
    category: "Kompakt",
    bodyType: "hatchback",
    catalogueRangeKm: 400,
    cataloguePriceFrom: 619_000,
    hasDetailPage: false,
  },
  {
    brandName: "Škoda",
    brandSlug: "skoda",
    modelName: "Škoda Elroq",
    modelSlug: "elroq",
    category: "SUV",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/skoda/elroq`,
    catalogueRangeKm: 581,
    cataloguePriceFrom: 799_000,
    hasDetailPage: true,
  },
  {
    brandName: "Škoda",
    brandSlug: "skoda",
    modelName: "Nová Škoda Enyaq",
    modelSlug: "enyaq",
    category: "SUV",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/skoda/enyaq`,
    catalogueRangeKm: 581,
    cataloguePriceFrom: 1_015_000,
    hasDetailPage: true,
  },
  {
    brandName: "Kia",
    brandSlug: "kia",
    modelName: "Kia EV2",
    modelSlug: "ev2",
    category: "Městský elektromobil",
    bodyType: "city",
    catalogueRangeKm: 440,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "Kia",
    brandSlug: "kia",
    modelName: "Kia EV3",
    modelSlug: "ev3",
    category: "Rodinný crossover",
    bodyType: "suv",
    detailUrl: `${BEZEMISI_BASE_URL}/elektromobily/kia/ev3`,
    catalogueRangeKm: 605,
    cataloguePriceFrom: 899_980,
    hasDetailPage: true,
  },
  {
    brandName: "Kia",
    brandSlug: "kia",
    modelName: "Kia EV4",
    modelSlug: "ev4",
    category: "Kompakt",
    bodyType: "hatchback",
    catalogueRangeKm: 630,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "Kia",
    brandSlug: "kia",
    modelName: "Kia EV5",
    modelSlug: "ev5",
    category: "Rodinný SUV",
    bodyType: "suv",
    catalogueRangeKm: 530,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "Volkswagen",
    brandSlug: "volkswagen",
    modelName: "Volkswagen ID. Polo",
    modelSlug: "id-polo",
    category: "Městský elektromobil",
    bodyType: "hatchback",
    catalogueRangeKm: 400,
    priceUnavailable: true,
    hasDetailPage: false,
  },
  {
    brandName: "CUPRA",
    brandSlug: "cupra",
    modelName: "CUPRA Raval",
    modelSlug: "raval",
    category: "Městský elektromobil",
    bodyType: "hatchback",
    catalogueRangeKm: 440,
    cataloguePriceFrom: 719_900,
    hasDetailPage: false,
  },
  {
    brandName: "Ford",
    brandSlug: "ford",
    modelName: "Ford Puma Gen-E",
    modelSlug: "puma-gen-e",
    category: "Kompaktní SUV",
    bodyType: "suv",
    catalogueRangeKm: 376,
    cataloguePriceFrom: 868_900,
    hasDetailPage: false,
  },
  {
    brandName: "Ford",
    brandSlug: "ford",
    modelName: "Ford Capri",
    modelSlug: "capri",
    category: "SUV",
    bodyType: "suv",
    catalogueRangeKm: 627,
    cataloguePriceFrom: 1_159_900,
    hasDetailPage: false,
  },
];

export const COMMERCIAL_DISCOVERY_URLS = [
  `${BEZEMISI_BASE_URL}/elektromobily/hyundai/inster`,
  `${BEZEMISI_BASE_URL}/kontakt`,
  `${BEZEMISI_BASE_URL}/operativni-leasing`,
  `${BEZEMISI_BASE_URL}/akcni-nabidky`,
];

export function listDiscoveryUrls() {
  const modelUrls = DISCOVERED_CATALOGUE_MODELS.filter((model) => model.detailUrl).map(
    (model) => model.detailUrl!,
  );
  return [...new Set([`${BEZEMISI_BASE_URL}/elektromobily`, ...modelUrls, ...COMMERCIAL_DISCOVERY_URLS])];
}
